### ISSUE TITLE
can't open rb3 ui/track/char milos

### ISSUE THREAD

**Issue by jnackmclain** [ihatecompvir/MiloEditor#2]
attempted rb3 /ui/main/main_hub.milo
and /ui/track/mtv_overlay.milo

Both gave the same error
![image](https://github.com/user-attachments/assets/c7eaa9d1-07eb-4cf9-a32d-3f60c1906a59)

Tried to open /char/main/bass/pablo_triburst.milo (any) gave
![image](https://github.com/user-attachments/assets/a0082969-277e-499a-a4af-38ca2b0f908d)

built from latest commit, release target

**Comment by ihatecompvir** [comment]
fixed
